categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'changelog:breaking'
  - title: '🚀 Features'
    labels:
      - 'changelog:feature'
  - title: '🐞 Bug Fixes'
    labels:
      - 'changelog:fix'
  - title: '✨ Enhancements'
    labels:
      - 'changelog:enhancement'
  - title: '📖 Documentation'
    labels:
      - 'changelog:docs'
  - title: '🧰 Maintenance'
    labels:
      - 'changelog:chore'
      - 'changelog:ci'
      - 'changelog:dependency'
version-resolver:
  major:
    labels:
      - 'changelog:breaking'
  minor:
    labels:
      - 'changelog:feature'
  default: patch
