name: require-pr-label

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-labels
        run: |
          labels=$(yq '[.categories[].labels] | flatten | unique | sort | @tsv' .github/release-drafter.yml | tr '\t' ',')
          echo "labels=$labels" >> "${GITHUB_OUTPUT}"
      - id: check-labels
        uses: mheap/github-action-required-labels@5847eef68201219cf0a4643ea7be61e77837bbce # v5.4.1
        with:
          mode: minimum
          count: 1
          use_regex: false
          labels: |
            ${{ steps.get-labels.outputs.labels }}
